/// Flutter icons Prison
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Prison
///      fonts:
///       - asset: fonts/Prison.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Prison {
  Prison._();

  static const _kFontFam = 'Prison';
  static const String? _kFontPkg = null;

  static const IconData prison = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
